#! /usr/bin/env perl
   use strict;
   use 5.010;
   use autodie;
   use Getopt::Long;
   my($in,$out,$help);
   GetOptions("in=s"=>\$in,"out=s"=>\$out,"help"=>\$help);
   if($in and $out){
     open IN,'<',$in;
     open OUT,'>',$out;

     my @seqs;
     while(<IN>){
       chomp;
       if(m/^>/){
         print OUT $_."\n";
      }else{
         push @seqs,$_;
      }
    }
     close IN;

     my $seq=join("",@seqs);

     while($seq){
       print OUT substr($seq,0,50)."\n";
       $seq=substr($seq,50);
    }

     close OUT;

   }elsif($help){
      say"This script aims to \n
      --in:the input file;\n
      --out:the result file;\n
      --help:the help!\n";
   }else{
      print "Please read the help!\n";
   }
